config/routes.rb
Rails.application.routes.draw do

# en este caso site sería el nombre del controlador y el método home
  get "/" => "site#home"

  get "/contact" => "site#contact"

  resources :projects, only: [:index, :show] do 
    resources :entries, only: [:index, :create, :new, :edit, :update, :destroy]
  end

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :project

  validates :hours, :minutes, numericality: true
  validates :hours, :minutes, :date, :project_id, presence: true
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :entries, dependent: :destroy

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :name, length: { maximum: 30 }
  #validates :name, format:{ with: /\w\s[^_]/ }
  validates :name, format:{ with: /\A[a-zA-ZÑñ
    0-9\ ]+\z/ }

  def self.clean_old
   where("created_at < ?", Time.now - 7.days).destroy_all
  end
  def self.iron_find(id)
    where(id: id).first
  end
  def self.last_created_projects(num_projects)
    order(created_at: :desc).limit(num_projects)
  end
  def total_hours_in_month(month, year)
    from = Date.new(year, month, 1)
    to = from.end_of_month
    #selecciona sólo las que están en este rango
    entries = self.entries.where(date: from..to)
    entries.pluck(:hours).sum()
    #entries.to_a.sum(&:hours)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def render_404(params)
    Rails.logger.warn("Tried to acces #{params} wich did not exists")
    render "layouts/404"
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  def index
    @project = Project.find_by id: params[:project_id]
    @entries = @project.entries
    @date = Date.today
  end

  def new
    #Identificas el proyecto a través del parámetro definido en la URL
    @project = Project.find params[:project_id]
    #Creas una nueva entrada (aunque sin salvarla). Posteriormente 
    #le otorgaremos valores a los parámetros a través del formulario
    @entry = @project.entries.new
  end

  def create
    #find the project
    @project = Project.find params[:project_id]
    #new entry for that project with attributes from params[:entry]
    @entry = @project.entries.new(entry_params)
    #Try to save it
    if @entry.save 
      flash[:notice] = "Entry created correctly"
      redirect_to action: "index", controller: "entries", project_id: @project.id
    else
      flash[:alert] = "You have some errors:"
      render "new"
    end
  end

  def edit
    @project = Project.find params[:project_id]
    @entry = @project.entries.find params[:id]
  end

  def update
    @project = Project.find params[:project_id]
    @entry = @project.entries.find params[:id]
    
    if @entry.update_attributes(entry_params)
      redirect_to project_entries_path
    else
      render "edit"
    end
  end

  def destroy
    project = Project.find params[:project_id]
    entry = project.entries.find params[:id]
    entry.destroy
    redirect_to project_entries_path
  end


  private

  #De esta manera podremos utilizar el método project a la hora de encontrar
  # def project
  #   @_project ||= Project.find(params[:project_id])
  # end

  def entry_params
    params.require(:entry).permit(:hours, :minutes, :date)
  end


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.last_created_projects(10)
    if @projects.empty? 
      render("site/no_projects") 
    end
  end

  def show
    @project = Project.find_by(id: params[:id]) || render_404(params)
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def home
    render "home" #name of the view template
  end
  def contact
    render "contact"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Displays the messages in the views
  # In the view should be called <%= flash_messages %>
  def flash_messages
    if flash[:notice]
      flash_format(flash[:notice], "notice")
    elsif flash[:alert]
      flash_format(flash[:alert], "alert")
    end 
  end

private
#Private methods are used only inside the helper
  def flash_format(flash, clase)
    content_tag :div, class: "message #{clase}" do 
      content_tag :p do  
          flash
        end
      end
  end


end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def project_hours_for_month(project, date)
    project.total_hours_in_month(date.month, date.year)
  end
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/entries/_form.html.erb
<% if flash[:alert] %>
  <%= flash[:alert] %>
<% end %>

<% if @entry.errors.any? %>
  <ul>
    <% @entry.errors.full_messages.each do |error|%>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>


<%= form_for [@project, @entry] do |f| %>
  <%= f.label :hours %>
  <%= f.text_field :hours %>
  <br>
  <%= f.label :minutes %>
  <%= f.text_field :minutes %>
  <br>
  <%= f.label :date %>
  <%= f.date_field :date %>
  <br>
  <%= f.submit "save" %>
<% end %>
<%= link_to("Back", project_entries_path(@project))%>

app/views/entries/edit.html.erb
<h2>Editing a new entry in <%= @project.name %></h2>
<%= render "form" %>

app/views/entries/index.html.erb
<%= flash_messages %>
<p><%= @project.name %></p>

<ul>
  <%@entries.each do |entry|%>
  <li><%= entry.hours %>h<%= entry.minutes %>m - <%= entry.date.strftime("%d/%m/%Y") %></li>
  <%= link_to("Edit", edit_project_entry_path(@project.id, entry.id)) %>
  <%= link_to("Delete", project_entry_path(@project.id, entry.id), method: :delete, data: {confirm: "Are you sure?"}) %>
  <% end %>

  <p>You have worked <%= project_hours_for_month(@project, @date) %> hours this month.</p>
  <%= link_to("Projects", projects_path)%>
  <%= link_to("Create entry", new_project_entry_path(@project))%>
</ul>

app/views/entries/new.html.erb
<h2>Creating a new entry in <%= @project.name %></h2>

<%= render "form" %>

app/views/layouts/404.html.erb
<h1>Error</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timetracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="wrapper">
    <header>
      <h2>Time tracking tool</h2>
    </header> 

    <%= yield %>

    <footer>IronHack - Rails introduction</footer>
  </div>
</body>
</html>

app/views/projects/index.html.erb
<h1>Estos son tus proyectos</h1>
<div class="projects_wrapper">
  <ul class="columns">
    <% @projects.each do |project| %>
      <li class="column is-3 card">
        <%= link_to(project.name, project_entries_path(project.id)) %>
        <% if project.description.present? %>
          <%= " - #{project.description}" %>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/projects/no_projects_found.html.erb
<h1>The Project you are trying to find does not exists</h1>

app/views/projects/show.html.erb
<h2><%= @project.name %></h2>
<p><%= @project.description %></p>

app/views/site/contact.html.erb
<h2>If you want to contact us please send an email to</h2>
<p>weberjavi@gmail.com</p>

app/views/site/home.html.erb
<h1>Welcome to this timetracking tool</h1>
<p>Ironhack powered</p>

app/views/site/no_projects.html.erb
<p>there are no projects</p>